"""link a transaction to its recurring expense

Revision ID: 08132dafd8be
Revises: f139fc98742b
Create Date: 2026-09-20 17:47:18.226635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08132dafd8be'
down_revision: Union[str, Sequence[str], None] = 'f139fc98742b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('recurring_expense_id', sa.Uuid(), nullable=True))
    # Named, so the downgrade can drop it.
    op.create_foreign_key('transactions_recurring_expense_id_fkey', 'transactions',
                          'recurring_expenses', ['recurring_expense_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_recurring_expense_id_fkey', 'transactions',
                       type_='foreignkey')
    op.drop_column('transactions', 'recurring_expense_id')
    # ### end Alembic commands ###
