"""inflation index values

Revision ID: 22b9e1c06179
Revises: 05fc339ddf1a
Create Date: 2026-09-20 18:30:29.035774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b9e1c06179'
down_revision: Union[str, Sequence[str], None] = '05fc339ddf1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inflation_indexes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('source', sa.Enum('api', 'manual', name='indexorigin'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'month', name='inflation_indexes_name_month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inflation_indexes')
    # ### end Alembic commands ###
