"""recurring expenses

Revision ID: 2828d263c01d
Revises: 744a9490889d
Create Date: 2026-09-19 20:47:30.717347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2828d263c01d'
down_revision: Union[str, Sequence[str], None] = '744a9490889d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_expenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    # The currency type is already in the database; only the column is new.
    sa.Column('currency', postgresql.ENUM('ARS', 'USD', name='currency',
                                          create_type=False), nullable=False),
    sa.Column('reference_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_day', sa.Integer(), nullable=False),
    sa.Column('is_fixed', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expected_day BETWEEN 1 AND 31', name='recurring_expenses_expected_day'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurring_expenses')
    # ### end Alembic commands ###
