"""import profiles, imports and categorization rules

Revision ID: 4257bfa13ab9
Revises: b1c2d3e4f5a6
Create Date: 2026-09-14 16:35:08.819328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4257bfa13ab9'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('date_format', sa.String(length=50), nullable=False),
    sa.Column('number_format', sa.Enum('comma_decimal', 'dot_decimal', name='numberformat'), nullable=False),
    sa.Column('sign_convention', sa.Enum('negative_is_expense', 'positive_is_expense', 'debit_credit_columns', name='signconvention'), nullable=False),
    sa.Column('ignore_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('categorization_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pattern', sa.String(length=250), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('origin', sa.Enum('manual', 'suggestion', name='ruleorigin'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern', name='categorization_rules_pattern')
    )
    op.create_table('imports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=250), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['import_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(
        'transactions_import_id_fkey', 'transactions', 'imports', ['import_id'], ['id']
    )
    op.create_unique_constraint(
        'budgets_category_month', 'budgets', ['category_id', 'month']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('budgets_category_month', 'budgets', type_='unique')
    op.drop_constraint('transactions_import_id_fkey', 'transactions', type_='foreignkey')
    op.drop_table('imports')
    op.drop_table('categorization_rules')
    op.drop_table('import_profiles')
    # ### end Alembic commands ###
