"""adjustment rules on recurring expenses

Revision ID: e0a578866323
Revises: 22b9e1c06179
Create Date: 2026-09-20 19:10:34.343492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Each kind fills its own columns and leaves the others null. Written out here
# rather than imported, so this migration keeps saying what it did today.
ADJUSTMENT_IS_COHERENT = """
    (adjustment_kind = 'none'
        AND adjustment_period_months IS NULL
        AND adjustment_start_month IS NULL
        AND adjustment_percentage IS NULL
        AND adjustment_index_name IS NULL)
    OR (adjustment_kind = 'percentage'
        AND adjustment_period_months IS NOT NULL
        AND adjustment_start_month IS NOT NULL
        AND adjustment_percentage IS NOT NULL
        AND adjustment_index_name IS NULL)
    OR (adjustment_kind = 'index'
        AND adjustment_period_months IS NOT NULL
        AND adjustment_start_month IS NOT NULL
        AND adjustment_index_name IS NOT NULL
        AND adjustment_percentage IS NULL)
"""


# revision identifiers, used by Alembic.
revision: str = 'e0a578866323'
down_revision: Union[str, Sequence[str], None] = '22b9e1c06179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    kind = postgresql.ENUM(
        'none', 'percentage', 'index', name='adjustmentkind', create_type=False
    )
    kind.create(op.get_bind())
    # The templates already there carry no Adjustment Rule.
    op.add_column('recurring_expenses', sa.Column('adjustment_kind', kind, nullable=False, server_default='none'))
    op.add_column('recurring_expenses', sa.Column('adjustment_period_months', sa.Integer(), nullable=True))
    op.add_column('recurring_expenses', sa.Column('adjustment_percentage', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('recurring_expenses', sa.Column('adjustment_index_name', sa.String(length=50), nullable=True))
    op.add_column('recurring_expenses', sa.Column('adjustment_start_month', sa.Date(), nullable=True))
    # ### end Alembic commands ###
    op.create_check_constraint(
        'recurring_expenses_adjustment_period',
        'recurring_expenses',
        'adjustment_period_months IS NULL OR adjustment_period_months >= 1',
    )
    op.create_check_constraint(
        'recurring_expenses_adjustment',
        'recurring_expenses',
        ADJUSTMENT_IS_COHERENT,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('recurring_expenses_adjustment', 'recurring_expenses')
    op.drop_constraint(
        'recurring_expenses_adjustment_period', 'recurring_expenses'
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_expenses', 'adjustment_start_month')
    op.drop_column('recurring_expenses', 'adjustment_index_name')
    op.drop_column('recurring_expenses', 'adjustment_percentage')
    op.drop_column('recurring_expenses', 'adjustment_period_months')
    op.drop_column('recurring_expenses', 'adjustment_kind')
    # ### end Alembic commands ###
    postgresql.ENUM(name='adjustmentkind').drop(op.get_bind())
