"""reviews and suggestions

Revision ID: f139fc98742b
Revises: 2828d263c01d
Create Date: 2026-09-20 14:44:57.884383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f139fc98742b'
down_revision: Union[str, Sequence[str], None] = '2828d263c01d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trigger', sa.Enum('recurring_monthly', 'month_end', 'manual', name='reviewtrigger'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='reviewstatus'), nullable=False),
    sa.Column('used_agent', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('note', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('add_transaction', name='suggestionkind'), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=250), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'expired', name='suggestionstatus'), nullable=False),
    sa.Column('rejection_reason', sa.String(length=250), nullable=True),
    sa.Column('result_id', sa.Uuid(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggestions')
    op.drop_table('reviews')
    # ### end Alembic commands ###
