/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransaccionesRouteImport } from './routes/transacciones'
import { Route as PresupuestosRouteImport } from './routes/presupuestos'
import { Route as BandejaRouteImport } from './routes/bandeja'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as IndexRouteImport } from './routes/index'

const TransaccionesRoute = TransaccionesRouteImport.update({
  id: '/transacciones',
  path: '/transacciones',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestosRoute = PresupuestosRouteImport.update({
  id: '/presupuestos',
  path: '/presupuestos',
  getParentRoute: () => rootRouteImport,
} as any)
const BandejaRoute = BandejaRouteImport.update({
  id: '/bandeja',
  path: '/bandeja',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/bandeja': typeof BandejaRoute
  '/presupuestos': typeof PresupuestosRoute
  '/transacciones': typeof TransaccionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/bandeja': typeof BandejaRoute
  '/presupuestos': typeof PresupuestosRoute
  '/transacciones': typeof TransaccionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/bandeja': typeof BandejaRoute
  '/presupuestos': typeof PresupuestosRoute
  '/transacciones': typeof TransaccionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ajustes' | '/bandeja' | '/presupuestos' | '/transacciones'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ajustes' | '/bandeja' | '/presupuestos' | '/transacciones'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/bandeja'
    | '/presupuestos'
    | '/transacciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  BandejaRoute: typeof BandejaRoute
  PresupuestosRoute: typeof PresupuestosRoute
  TransaccionesRoute: typeof TransaccionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transacciones': {
      id: '/transacciones'
      path: '/transacciones'
      fullPath: '/transacciones'
      preLoaderRoute: typeof TransaccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuestos': {
      id: '/presupuestos'
      path: '/presupuestos'
      fullPath: '/presupuestos'
      preLoaderRoute: typeof PresupuestosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bandeja': {
      id: '/bandeja'
      path: '/bandeja'
      fullPath: '/bandeja'
      preLoaderRoute: typeof BandejaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  BandejaRoute: BandejaRoute,
  PresupuestosRoute: PresupuestosRoute,
  TransaccionesRoute: TransaccionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
